# Generated by Django 4.0.3 on 2022-03-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0002_create_question_details_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Author', to='account.profile')),
                ('tag', models.ManyToManyField(to='forum.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Create_Question',
        ),
        migrations.DeleteModel(
            name='Details_Question',
        ),
    ]
