# Generated by Django 4.0.3 on 2022-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0004_alter_question_votelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votelist',
            field=models.ManyToManyField(to='account.profile'),
        ),
    ]
