# Generated by Django 4.0.3 on 2022-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0006_alter_question_votelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votelist',
            field=models.ManyToManyField(related_name='voteanswerslist', to='account.profile'),
        ),
    ]
