# Generated by Django 4.0.3 on 2022-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0007_alter_answer_votelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votelist',
            field=models.ManyToManyField(null=True, related_name='voteanswerslist', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='votelist',
            field=models.ManyToManyField(null=True, related_name='votequestionlist', to='account.profile'),
        ),
    ]
